### ISSUE TITLE
Make error

### ISSUE THREAD

**Issue by ottojo** [DougGore/picopi#5]
when following the instructions i get the following error:

pi@raspberrypi ~/picopi/pico/tts $ sudo make
g++ -L../lib/ strdup16to8.c strdup8to16.c svox_ssml_parser.cpp com_svox_picottsengine.cpp main.cpp -lexpat -lsvoxpico -I../compat/include/ -I../lib/ -fpermissive -o testtts
g++: error: com_svox_picottsengine.cpp: No such file or directory
Makefile:35: recipe for target 'all' failed
make: **\* [all] Error 1

**Comment by AmarOk1412** [comment]
Same issue here

**Comment by brosquinha** [comment]
I'm getting the same result here

**Comment by ucokzeko** [comment]
Same issue here

**Comment by ch3ll0v3k** [comment]
Me to. I like option piping option. Have some body solved this ?

**Comment by DougGore** [comment]
I had to remove the "com_svox_picottsengine.cpp" file for legal reasons earlier this year, however I think it's possible to remove this dependency. I will try and investigate if I get some time.

**Comment by ch3ll0v3k** [comment]
For every one who is looking for this util. See my repo.
https://github.com/ch3ll0v3k/picoPi2

**Comment by DougGore** [comment]
I have looked at fixing the testtts utility after having to remove a file for legal reasons. Unfortunately the utility had a big dependency on the removed file, however the TTS library itself is unaffected. It may be a while before I am able to implement a fix for the test application but the picotts.h file in the lib folder documents roughly what needs to be done to use the TTS engine.

**Comment by ishmael1851** [comment]
Thanks for all your work, Doug.  I took a look at the file you removed, and it appears to be under the Apache2 license as well, just like the rest of the package.  What were the specific legal reasons cited for removing that particular file?

**Comment by gmorenz** [comment]
I've got a working example that works with the C-api [here](https://github.com/gmorenz/pico-tts), that should avoid DMCA issues.
